/****** Object:  StoredProcedure [dbo].[sp_get_create_KeHoachChiTietBQP]    Script Date: 04/11/2022 8:48:59 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROC [dbo].[sp_get_create_KeHoachChiTietBQP]
    @KHTTCP_ID UNIQUEIDENTIFIER = NULL
AS
BEGIN
	SELECT
		TTCP_NVC.ID AS ID,
		TTCP_NVC.ID AS iID_KHTTTTCP_NhiemVuChiID,
		TTCP_NVC.sTenNhiemVuChi AS sTenNhiemVuChi,
		TTCP_NVC.iID_BQuanLyID AS iID_BQuanLyID,
		CONCAT(RTRIM(LTRIM(PB.sTen)), IIF(PB.sMota IS NULL OR RTRIM(LTRIM(PB.sMoTa)) = '', '', CONCAT(' - ', RTRIM(LTRIM(PB.sMoTa))))) AS sTenPhongBan,
		NULL AS iID_DonViID,
		NULL AS sTenDonVi,
		NULL AS iID_MaDonVi,
		TTCP_NVC.fGiaTri AS fGiaTriTTCP_USD,
		NULL AS fGiaTriBQP_USD,
		NULL AS fGiaTriBQP_VND,
		TTCP_NVC.sMaThuTu AS sMaThuTu,
		TTCP_NVC.iID_ParentID AS iID_ParentID,
		CAST(1 AS BIT) AS bIsTTCP,
		IIF(CheckAction.ID IS NOT NULL, CAST(1 AS BIT), CAST(0 AS BIT)) AS bIsAction,
		IIF(CheckAction.ID IS NOT NULL, CAST(0 AS BIT), CAST(1 AS BIT)) AS bIsHasChild,
		CAST('/' + REPLACE(sMaThuTu, '.', '/') + '/' as HIERARCHYID) AS Sort
	FROM NH_KHTongTheTTCP AS TTCP
	LEFT JOIN NH_KHTongTheTTCP_NhiemVuChi AS TTCP_NVC ON TTCP.ID = TTCP_NVC.iID_KHTongTheID
	LEFT JOIN NS_PhongBan AS PB ON TTCP_NVC.iID_BQuanLyID = PB.iID_MaPhongBan
	LEFT JOIN (SELECT ID FROM NH_KHTongTheTTCP_NhiemVuChi AS NVMCheck
		WHERE NOT EXISTS (SELECT 1 FROM NH_KHTongTheTTCP_NhiemVuChi AS NVPCheck WHERE NVPCheck.iID_ParentID = NVMCheck.ID)) AS CheckAction ON TTCP_NVC.ID = CheckAction.ID
	WHERE @KHTTCP_ID IS NULL OR TTCP.ID = @KHTTCP_ID
	ORDER BY Sort
END
GO

