ALTER TABLE VDT_QT_BCQuyetToanNienDo_ChiTiet_01 ADD iID_LoaiCongTrinh uniqueidentifier
ALTER TABLE VDT_QT_BCQuyetToanNienDo_PhanTich ADD iID_LoaiCongTrinh uniqueidentifier
ALTER TABLE VDT_TongHop_NguonNSDauTu ADD iID_LoaiCongTrinh uniqueidentifier
ALTER TABLE VDT_KT_KhoiTao_DuLieu_ChiTiet ADD iID_LoaiCongTrinh uniqueidentifier